### ISSUE TITLE
Heel mooi responsive op desktop, tablet en mobile 

### ISSUE THREAD

**Issue by ArexanK** [zenitba/Meesterproef#1]
<img width="1377" alt="Screenshot 2024-05-21 at 21 40 29" src="https://github.com/zenitba/Meesterproef/assets/94745953/47a894a3-70f9-49ae-b3b8-9d725fe96ff5">

<img width="1194" alt="Screenshot 2024-05-21 at 21 43 28" src="https://github.com/zenitba/Meesterproef/assets/94745953/faeba64d-4611-4f2d-8c47-6aa5fee5f150">

**Comment by zenitba** [comment]
Dankjewel😁
