### ISSUE TITLE
Performance LCP score van 85 :(

### ISSUE THREAD

**Issue by ArexanK** [zenitba/Meesterproef#2]
Lage score op LCP (Largest contenful paint).Hiermee wordt aangegeven hoe lang het duurt voordat het grootste element op een pagina aan de bezoeker wordt getoond.

Probeer Webp images te gebruiken, dit zijn voordelen:

- Compressie: WebP biedt zowel verliesvrije als verliesgevende compressie, wat resulteert in kleinere bestanden vergeleken met JPEG en PNG.
- Snelheid: Kleinere afbeeldingen laden sneller, wat direct bijdraagt aan een betere LCP-score.
- Efficiëntie: WebP behoudt een hoge beeldkwaliteit zelfs bij hogere compressieniveaus, wat zorgt voor snellere laadtijden zonder dat de visuele kwaliteit significant afneemt.

<img width="1388" alt="Screenshot 2024-05-21 at 21 48 51" src="https://github.com/zenitba/Meesterproef/assets/94745953/c6a9f45b-2000-4337-bc8c-dc172fe2d08f">

**Comment by zenitba** [comment]
Dankjewel voor de feedback😁
<img width="394" alt="Schermafbeelding 2024-05-23 om 12 51 46" src="https://github.com/zenitba/Meesterproef/assets/112856019/7d45770e-581a-4251-b1cd-fcfdeaf105d8">
