### ISSUE TITLE
accessibility: screenreader tab toets

### ISSUE THREAD

**Issue by ArexanK** [zenitba/Meesterproef#3]
Bij het testen van de navigatie met de Tab-toets, springt de focus direct naar het formulier onderaan de website. Het zou beter zijn als de Tab-toets eerst door het navbar gaat voordat deze naar het contactformulier onderaan de pagina springt. Dit verbetert de toegankelijkheid en gebruiksvriendelijkheid van de website.

**Comment by zenitba** [comment]
yes de :focus:visibility css weg gehaald
