### ISSUE TITLE
grijs achtergrond contrast check 

### ISSUE THREAD

**Issue by ArexanK** [zenitba/Meesterproef#4]
Even een dubbel check doen op contrast. 

<img width="1423" alt="Screenshot 2024-05-21 at 22 10 03" src="https://github.com/zenitba/Meesterproef/assets/94745953/c3e8bf47-44ca-437d-90b1-38b40d5b327f">

**Comment by zenitba** [comment]
De achtergrond kleur beetje donkerder gemaakd
